name: Dependency Updates

on:
  schedule:
    - cron: '0 2 * * 1' # Run every Monday at 2 AM UTC
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Check for outdated packages
        run: |
          npm outdated || true
          npm outdated --json > outdated.json || true

      - name: Update dependencies
        run: |
          # Update patch and minor versions
          npm update

          # Check if there are any updates
          if git diff --quiet package-lock.json; then
            echo "No updates available"
            exit 0
          fi

      - name: Run tests after update
        run: |
          npm run lint
          npm run types:check
          npm run build

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: Update dependencies'
          body: |
            ## 🔄 Dependency Updates

            This PR contains automated dependency updates.

            ### Changes
            - Updated patch and minor versions of dependencies
            - All tests and builds are passing

            ### Testing
            - ✅ Linting passed
            - ✅ Type checking passed
            - ✅ Build successful

            Please review the changes and merge if everything looks good.
          branch: chore/update-dependencies
          delete-branch: true

  security-updates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Run security audit
        run: |
          npm audit --audit-level=moderate
          npm audit fix --force || true

      - name: Check for changes
        run: |
          if git diff --quiet package-lock.json; then
            echo "No security updates needed"
            exit 0
          fi

      - name: Test after security fixes
        run: |
          npm run lint
          npm run types:check
          npm run build

      - name: Create Security Update PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'security: fix vulnerabilities'
          title: '🔒 Security: Fix vulnerabilities'
          body: |
            ## 🔒 Security Updates

            This PR contains automated security fixes.

            ### Security Fixes
            - Fixed security vulnerabilities found by `npm audit`
            - All tests and builds are passing

            ### Testing
            - ✅ Linting passed
            - ✅ Type checking passed
            - ✅ Build successful

            **Please review and merge promptly for security.**
          branch: security/fix-vulnerabilities
          delete-branch: true
          labels: security
