name: Pull Request Checks

on:
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened]

jobs:
  pr-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Check formatting
        run: npm run format:check

      - name: Type checking
        run: npm run types:check

      - name: Build project
        run: npm run build

      - name: Check bundle size
        run: |
          npm run build
          du -sh .next/static/chunks/* || true

      - name: Comment PR
        uses: actions/github-script@v6
        with:
          script: |
            const { execSync } = require('child_process');

            // Get build size info
            const buildInfo = execSync('du -sh .next/static/chunks/* || echo "No chunks found"', { encoding: 'utf8' });

            // Create comment body
            const commentBody = `
            ## 🚀 Build Summary

            ✅ **Linting**: Passed  
            ✅ **Type Check**: Passed  
            ✅ **Build**: Successful  

            ### Bundle Size
            \`\`\`
            ${buildInfo}
            \`\`\`

            ### Next Steps
            - Review the changes carefully
            - Test the functionality
            - Merge when ready
            `;

            // Post comment
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });

  preview-deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy Preview to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          github-comment: true
          working-directory: ./
